on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{secrets.Devolper}} --password ${{secrets.cs}}

      - name: "Building Docker Image"
        run: docker build -t ${{secrets.Devolper}}/myimage .

      - name: "Pushing Docker Hup"
        run: docker push ${{secrets.Devolper}}/myimage .

    
          


